spring:
    profiles:
        active: dev
    application:
        name: kou-app-api
    jpa:
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true

server:
    port: 8080
    shutdown: graceful

management:
    endpoints:
        web:
            exposure:
                include: health,info
    endpoint:
        health:
            show-details: when-authorized

google:
    oauth2:
        client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
