spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/usagi_app_local
        username: admin
        password: 1234qwer
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

    data:
        redis:
            host: localhost
            port: 6379
            password:

jwt:
    secret: ${USAGI_LOCAL_JWT_SECRET}
    access-token-expire-duration: 1920000
    refresh-token-expire-duration: 1209600000

logging:
    level:
        com.kou.kouappapi: DEBUG
        org.springframework.web: DEBUG
        org.springframework.security: DEBUG

google:
    oauth2:
        playground: ${GOOGLE_OAUTH2_PLAYGROUND}

cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
    folder:
        profile: usagi-app/local/profile
        diary: usagi-app/local/diary


springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
