spring:
    datasource:
        url: ${USAGI_DEV_DB_URL}
        username: ${USAGI_DEV_DB_USERNAME}
        password: ${USAGI_DEV_DB_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false

    data:
        redis:
            host: ${USAGI_DEV_REDIS_HOST:localhost}
            port: 6379
            password: ${USAGI_DEV_REDIS_PASSWORD:}

logging:
    level:
        com.usagi.usagiappapi: DEBUG
        org.springframework.web: DEBUG
        org.springframework.security: DEBUG

jwt:
    secret: ${USAGI_DEV_JWT_SECRET}
    access-token-expire-duration: 1800000
    refresh-token-expire-duration: 1209600000

cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
    folder:
        profile: usagi-app/dev/profile
        diary: usagi-app/dev/diary

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
