spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/kou_app_local
        username: admin
        password: 1234qwer
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

server:
    port: 8080

logging:
    level:
        com.kou.kouappapi: DEBUG
        org.springframework.web: DEBUG
        org.springframework.security: DEBUG

jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 3600000

cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
    folder:
        profile: kou-app/local/individual/profile
