spring:
    datasource:
        url: ${KOU_DEV_DB_URL}
        username: ${KOU_DEV_DB_USERNAME}
        password: ${KOU_DEV_DB_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false

server:
    port: 8080

logging:
    level:
        com.kou.kouappapi: DEBUG
        org.springframework.web: DEBUG
        org.springframework.security: DEBUG

jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 3600000
