--
-- PostgreSQL database dump
--
-- Dumped from database version 15.15
-- Dumped by pg_dump version 18.3
-- Flyway baseline: 운영 DB(usagiapp) 현재 스키마 스냅샷

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activity_category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.activity_category (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    name character varying(255),
    user_id bigint
);


--
-- Name: activity_category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.activity_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activity_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: diary; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.diary (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    content character varying(255),
    date date,
    emotion smallint,
    image_id character varying(255),
    user_id bigint,
    CONSTRAINT diary_emotion_check CHECK (((emotion >= 0) AND (emotion <= 7)))
);


--
-- Name: diary_activity_category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.diary_activity_category (
    id bigint NOT NULL,
    activity_category_id bigint NOT NULL,
    diary_id bigint NOT NULL
);


--
-- Name: diary_activity_category_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.diary_activity_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.diary_activity_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: diary_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.diary ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.diary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_token (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone,
    token_hash character varying(500),
    user_id bigint NOT NULL
);


--
-- Name: refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    name character varying(255),
    password character varying(255),
    profile_image_id character varying(255),
    provider character varying(255),
    provider_id character varying(255),
    role character varying(255),
    status character varying(255),
    deleted_at timestamp(6) without time zone,
    CONSTRAINT users_provider_check CHECK (((provider)::text = ANY ((ARRAY['GOOGLE'::character varying, 'APPLE'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'WITHDRAWN'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: activity_category activity_category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_category
    ADD CONSTRAINT activity_category_pkey PRIMARY KEY (id);


--
-- Name: diary_activity_category diary_activity_category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diary_activity_category
    ADD CONSTRAINT diary_activity_category_pkey PRIMARY KEY (id);


--
-- Name: diary diary_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diary
    ADD CONSTRAINT diary_pkey PRIMARY KEY (id);


--
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- Name: diary_activity_category ukixk7vll22uccepn0443pec5qk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diary_activity_category
    ADD CONSTRAINT ukixk7vll22uccepn0443pec5qk UNIQUE (diary_id, activity_category_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: uq_users_email_active; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_users_email_active ON public.users USING btree (email) WHERE (deleted_at IS NULL);


--
-- Name: uq_users_provider_active; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_users_provider_active ON public.users USING btree (provider, provider_id) WHERE (deleted_at IS NULL);


--
-- Name: diary_activity_category fk3ft7x8deth53a7v0un1vifxtn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diary_activity_category
    ADD CONSTRAINT fk3ft7x8deth53a7v0un1vifxtn FOREIGN KEY (diary_id) REFERENCES public.diary(id);


--
-- Name: diary fk74rd0bn5raxejw2ukenelbdmt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diary
    ADD CONSTRAINT fk74rd0bn5raxejw2ukenelbdmt FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: activity_category fknyw3ah9i7b9myc376aw8jyrr7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_category
    ADD CONSTRAINT fknyw3ah9i7b9myc376aw8jyrr7 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: diary_activity_category fkssm1vpfaiifsa0g52hjpsahi6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diary_activity_category
    ADD CONSTRAINT fkssm1vpfaiifsa0g52hjpsahi6 FOREIGN KEY (activity_category_id) REFERENCES public.activity_category(id);


--
-- PostgreSQL database dump complete
--
