package com.kou.kouappapi.enums

enum class AuthError {
    AUTH_REQUIRED_PROFILE_INFO_MISSING,
    AUTH_EMAIL_NOT_VERIFIED,
    AUTH_PROVIDER_NOT_SUPPORTED,
    AUTH_EMAIL_ALREADY_REGISTERED,
    AUTH_INVALID_ID_TOKEN,
    AUTH_GENERATE_TOKEN_FAILED,
    AUTH_TOKEN_EXPIRED,
    AUTH_UNAUTHORIZED_TOKEN_ACCESS,
}
